### ISSUE TITLE
MSFS2024 not found

### ISSUE THREAD

**Issue by EisernUnion** [Fragtality/PilotsDeck#81] opened 2024-11-29 14:43 UTC
Hi, with the newest Version 0.8.3-202411272125 only MSFS2020 is found, MS2024 is ignored. In the meantime i added it manually by adding "FlightSimulator2024" in the PluginConfig.json within SimBinaries.MSFS.

The folder

-  %localappdata%\Packages\Microsoft.Limitless_8wekyb3d8bbwe\LocalCache\

exists.

I installed MSFS2024 in this folder during Setup

-  H:\XBoxGames\Microsoft Flight Simulator 2024"

My custom path of MSFS is (UserCfg.opt)

-  InstalledPackagesPath "H:\MSFS2024\"

![image](https://github.com/user-attachments/assets/970ab4e3-4ac1-48b5-96e0-5f93620d273a)

**Comment by Fragtality** [comment] 2024-11-29 23:00
Check the latest Dev Build: https://github.com/Fragtality/PilotsDeck/blob/master/Install-PilotsDeck-latest.exe
(It is not your first Rodeo here - you could have checked that first. The last Commit exactly solved that Problem 😉 )

> In the meantime i added it manually by adding "FlightSimulator2024" in the PluginConfig.json within SimBinaries.MSFS.

Could Hint! There was an Issue with updating the config on startup! (adding that name)

**Comment by EisernUnion** [comment] 2024-11-29 23:22
Im sorry :) i always forget to take a look into more recent commits :/
Its working (editing the config worked also fine (except GSX , but it's GSX, so^^)
Thx and sorry again

**Comment by Fragtality** [comment] 2024-11-29 23:50
No sorry needed, no worries - was just a Reminder that sometimes save *your* Time filing an Issue 😅 

Yeah sure, it is easily fixable in the Config (one Reason to not hardcode it anymore) - still that was very good Point because the automatic Update of the File didn't work as intended - so another Bug squashed 😃

**Comment by EisernUnion** [comment] 2024-11-30 00:06
slightly off-topic... any chance a for Fenix2GSX Update?

**Comment by Fragtality** [comment] 2024-11-30 00:09
Aren't you in the GSX Discord? Or V1 Discord?
Postet the latest Dev-Build there!
(Can't provide it like with PilotsDeck because the Binary is too big :/ )

But here it is: https://www.mediafire.com/file/qlk232ffix7whzf/Fenix2GSX-Installer-v0.4.17.exe/file

**Comment by EisernUnion** [comment] 2024-11-30 17:41
Not yet ..... thx works fine ..... msfs 2024 is near to work as msfs2020 ... the rest are issues ms/asobo has to fix (this toolbar becoming visible on mouse move drives me crazy :)

**Comment by tron9944** [comment] 2024-12-05 18:51
Hey! Trying to get PilotsDeck up and running for MSFS2024. I notice the installer updates MSFS2020, but does not detect MSFS2024 (same as above).  The [Install-PilotsDeck-latest.exe](https://github.com/Fragtality/PilotsDeck/blob/master/Install-PilotsDeck-latest.exe) link did not seem to work for me... downloaded a json file instead and I'm unsure of how to proceed without an actual installer.


And am using the latest installer.   24 is installed in: F:\XboxGames\Microsoft Flight Simulator 2024     and    my packages folder is F:\Microsoft Flight Simulator 2024

Thanks in advance for any help.

**Comment by Fragtality** [comment] 2024-12-05 21:37
Fixed with Version 0.8.4

**Closed by Fragtality** 2024-12-05 21:37 UTC
