### ISSUE TITLE
Control is missing offset On/Off value in dynamic button

### ISSUE THREAD

**Issue by rkantos** [Fragtality/PilotsDeck#6] opened 2021-04-09 03:59 UTC
The "Dynamic Button" is missing the offset On/Off values for the control/single press function. It exists in the long press control.

![image](https://user-images.githubusercontent.com/16664350/114126215-b0314200-9900-11eb-84ff-02c91be3f3c6.png)

![image](https://user-images.githubusercontent.com/16664350/114126418-1027e880-9901-11eb-839c-de30f59077d8.png)

**Comment by Fragtality** [comment] 2021-04-18 11:06
That is working as intended!

The underlying "assumption" for the "Dynamic Button" is that the Action and Control Status Addresses are the same (for Offsets & Lvar Actions) so the Values for "On" and "Off" are the same in both directions (read & write).
To allow more flexibility for the Second Control, it has its own On & Off Values (for Offsets & Lvar Actions). Although it is also evaluated to the same Control Status Address/Value to toggle.
Or in other Words: The current Value/State to be toggled is the same for the normal and second Control (on a Dynamic Button).

This is expressed in the Readme by:
_"For Offset and Lvar Actions: Since the Button knows the real current State of a Switch in the Sim, it will send the correct toggled Value to the Sim when pushed. If current Value is neither On nor Off, the Off Value will be send. If the Long Press Option is configured (and is also a Offset/Lvar Action), their On/Off States are also evaluated against the Control Status Value!
The Assumption is that Action Address and Address are the same Offset or Lvar, but if you have the Use-Case that they have to be different, you can configure it that way! Just mind that the same On/Off Values will be used for both reading and writing."_

If this is a Bug Report only, I'd close this issue (since working as intended & described).
If this is a Feature Request I'd need more information.

**Comment by rkantos** [comment] 2021-04-18 17:56
Issue expanded on in https://github.com/Fragtality/PilotsDeck/issues/9#issuecomment-822032256

**Comment by Fragtality** [comment] 2021-04-21 17:30
Will close this Issue, topic is further discussed in Issue #9

**Closed by Fragtality** 2021-04-21 17:30 UTC
Labels: question
